### ISSUE TITLE
Homepage tagline typo

### ISSUE THREAD

**Issue by a-kriya** [jamstack/jamstack.org#569]
I think the `delivers` in `The modern way to build [Websites and Apps] that delivers better performance` should be `deliver` instead.

**Comment by sandypockets** [comment]
I think this is up for a bit of interpretation. It really depends on the context that the author is using it in. 

If the 'modern way' is what delivers better performance, then `delivers` is correct. But if the 'Websites and Apps' are what is delivering the better performance, then `deliver` is correct. 

With that in mind, I think that `delivers` is still correct as is, because it's the JAM Stack itself, the method, that is delivering that improved performance _of_ the Websites and Apps.

**Comment by zachleat** [comment]
This sparked a fairly lengthy and controversial 😅 debate on our internal Slack 😅

That said, it came out to be a wash—there was no clear consensus either way so I think we’ll probably leave it as is!

I do appreciate the report and for the record I agree with @a-kriya here 😇

**Comment by a-kriya** [comment]
@zachleat 'Least it got some consideration! Thanks for sharing.

Perhaps some alternatives that reduce the ambiguity may be more agreeable:

>The modern way to build (highly performant | blazing fast) [Websites and Apps]

These don't seem to flow as well, though. No big.

**Comment by westurner** [comment]
No, you look like idiots from the first sentence. JAMstack performance cannot be measured.

😄

Why is this still broken?

**Comment by westurner** [comment]
Here's a PR that fixes this glaring issue: https://github.com/jamstack/jamstack.org/pull/667
